# Generated by Django 6.1.1 on 2026-09-29 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(primary_key=True, serialize=False)),
                ('device_kind', models.CharField(max_length=6)),
                ('last_seen_at', models.DateTimeField()),
                ('last_timestamp_ms', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TelemetrySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=9)),
                ('timestamp_ms', models.BigIntegerField()),
                ('motion', models.JSONField(blank=True, null=True)),
                ('body_pose', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='telemetry.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'timestamp_ms'], name='sample_device_time_idx'), models.Index(fields=['device', 'type', 'timestamp_ms'], name='sample_device_type_time_idx')],
            },
        ),
    ]
